### IP NAT ###
ip_nat:
  kernel_buffer_size: 64
  pools:
    - name: prefix_16
      prefix_length: 16
      ranges:
        - first_ip: 10.0.0.1
          last_ip: 10.0.255.254
        - first_ip: 10.1.0.0
          last_ip: 10.1.255.255
          first_port: 1024
          last_port: 65535
      utilization_log_threshold: 1
    - name: prefix_32
      prefix_length: 32
      ranges:
        - first_ip: 10.2.0.1
          last_ip: 10.2.0.1
    - name: prefix_24
      prefix_length: 24
      ranges:
        - first_ip: 10.3.0.1
          last_ip: 10.3.0.254
        - first_ip: 10.3.1.0
          last_ip: 10.3.1.255
          first_port: 1024
          last_port: 65535
      utilization_log_threshold: 100
  synchronization:
    description: 'test sync config'
    expiry_interval: 60
    local_interface: Ethernet1
    peer_address: 1.1.1.1
    port_range:
      first_port: 1024
      last_port: 65535
      split_disabled: true
    shutdown: true
  translation:
    address_selection:
      any: true
      hash_field_source_ip: true
    counters: true
    low_mark:
      percentage: 50
      host_percentage: 50
    max_entries:
      limit: 100000
      host_limit: 1000
      ip_limits:
        - ip: 10.0.0.1
          limit: 100
        - ip: 10.0.0.2
          limit: 200
    timeouts:
      - protocol: udp
        timeout: 3600
      - protocol: tcp
        timeout: 7200
