# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---
- name: Verify Requirements
  tags: [always, avd_req]
  delegate_to: localhost
  when: avd_requirements is not defined
  arista.avd.verify_requirements:
    requirements: "{{ lookup('file', requirements_path ~ '/requirements.txt').splitlines() }}"
    avd_ignore_requirements: "{{ avd_ignore_requirements | default(false) }}"
  vars:
    requirements_path: "{{ (role_path | split('/'))[0:-2] | join('/') }}"
  run_once: true
  register: avd_requirements

- name: Create required output directories if not present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ eos_validate_state_dir }}"
    - "{{ output_dir }}"
    - "{{ test_catalogs_dir }}"
  delegate_to: localhost
  run_once: true
  check_mode: false
  tags:
    - always

- name: Include device intended structured configuration variables
  ansible.builtin.include_vars: "{{ filename }}"
  delegate_to: localhost
  when: structured_config is not defined and lookup('first_found', filename, skip=True, errors='ignore')
  vars:
    filename: "{{ structured_dir }}/{{ inventory_hostname }}.{{ avd_structured_config_file_format }}"
  tags:
    - always

#########################################
##  Run eos_validate_state using ANTA  ##
#########################################

- name: Run eos_validate_state_runner leveraging ANTA
  ansible.builtin.include_tasks: "anta_tests.yml"
  when: use_anta
  tags:
    - always

#####################################
##  Run ansible assert eos_validate_state  ##
#####################################

- name: Run ansible assert tests
  ansible.builtin.include_tasks: "ansible_tests.yml"
  when: not use_anta
  tags:
    - always

####################################
##       Validation Reports       ##
####################################

- name: Create reports
  ansible.builtin.include_tasks: "reports.yml"
  tags:
    - always
    - reports
